### ISSUE TITLE
Create Python Flask Cloud Foundry in IBM Cloud

### ISSUE THREAD

**Issue by jp1130** [devops-suppliers/suppliers#37]
**As a** supplier manager
**I need** cloud microservice set up 
**So that** I can access supplier resources in real-time

**Assumptions:**
* Cloud Account set up 

**Acceptance Criteria:**

Given that supplier manager needs access to suppliers database
When I need to add/update/delete suppliers 
Then I can perform those actions directly in the database

**Steps:**
* Create IBM Cloud account
* Invite other members of your team to the IBM Cloud account
* Create a  Python Flask Cloud Foundry application in IBM Cloud
* Naming is very important so please follow the following format:
       *nyu-supplier-service-s20*
(The full URL will then be:
nyu-supplier-service-s20.us-south.cf.appdomain.cloud)

---EXAMPLE---
Make the hit counter persistently survive service restarts

As a User
I need the hit counter to persist the last known count
So that I don't loose track of the count after the service is restarted

Assumptions:
	• We will use Redis as the persistent store
	• A Redis service from Bluemix should be used

Acceptance Criteria:
When	I	advance	the	hit	counter	to	2																
And		I	restart	the	hit	counter	services												
And		I	call	the	hit	counter	URL																				
Then	I	should	see	3	returned	from	the	service	

---End of EXAMPLE---

**Comment by liyana-fauzi** [comment]
Would like to propose a change to the story. See below:

**As a** developer
**I need** cloud microservice set up 
**So that** I can push my app to the cloud service

**Assumptions:**
* All developers have an IBM Cloud account

**Acceptance Criteria:**

Given that the developer needs to use the cloud service
When I need to access the cloud service
Then I can manage my app on the IBM cloud service

**Steps:**
* Create IBM Cloud account
* Invite other members of your team to the IBM Cloud account
* Create a  Python Flask Cloud Foundry application in IBM Cloud
* Naming is very important so please follow the following format:
       *nyu-supplier-service-s20*
(The full URL will then be:
nyu-supplier-service-s20.us-south.cf.appdomain.cloud)
